### ISSUE TITLE
Minecraft can't launch

### ISSUE THREAD

**Issue by Lonexoli** [guihkx/com.teamshiginima.ShiginimaLauncher#2]
Since yesterday, I can't launch Minecraft. When I press the "Start" button, the game crashes before the window is created. The game used to work perfectly fine...

```OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Completely ignored arguments: [--workdir, /home/loloreel/.var/app/com.teamshiginima.ShiginimaLauncher/data/minecraft]
[15:18:49] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:18:50] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:97) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at djz.a(SourceFile:625) [1.16.4.jar:?]
	at djz.<init>(SourceFile:409) [1.16.4.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:177) [1.16.4.jar:?]
[15:18:50] [Render thread/INFO]: Setting user: loloreel
[15:18:50] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
Gtk-Message: 15:18:51.112: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:18:51.112: Failed to load module "canberra-gtk-module"
sh: ligne 3: xprop : commande introuvable
sh: ligne 3: xprop : commande introuvable
[15:18:51] [Render thread/WARN]: Failed to create window: 
dez$a: GLFW error 65545: GLX: Failed to find a suitable GLXFBConfig
	at dez.b(SourceFile:216) ~[1.16.4.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at dez.<init>(SourceFile:90) ~[1.16.4.jar:?]
	at eau.a(SourceFile:21) ~[1.16.4.jar:?]
	at djz.<init>(SourceFile:461) ~[1.16.4.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:177) [1.16.4.jar:?]
```

**Comment by guihkx** [comment]
Not really sure what it could be, as I'm also on 1.16.4 and it still works for me. I also did a clean installation on a virtual machine with Kubuntu 20.10 with Wayland it works just fine there:

![Screenshot from 2021-02-10 14-55-02](https://user-images.githubusercontent.com/626206/107550588-fa6f9e80-6baf-11eb-8dc0-90e1ecc51b1c.png)


Is your log file incomplete by any chance? Can you please double-check: `~/.var/app/com.teamshiginima.ShiginimaLauncher/data/minecraft/logs/latest.log`

I would also try renaming the `com.teamshiginima.ShiginimaLauncher` folder to something else (temporarily), then try running the launcher again so it creates a fresh Minecraft installation. If the game runs, then you can perhaps try copying your stuff from the older folder to the new one.

**Comment by luni3359** [comment]
No problems on my end either

**Comment by Lonexoli** [comment]
Thanks for the answer!
What I sent is the entire log. Also, I tried what you said but I still have the same problem.

**Comment by guihkx** [comment]
Well, it sounds like a recent system update (video driver, most likely) broke Flatpak. Did you try running `flatpak update`?

If you did, then please provide the following information:

* Linux distribution
* GPU
* Video driver and version
* Display server (X11 or Wayland)

And a list of installed Flatpak apps:

```
flatpak list
```

Thanks.

**Comment by Lonexoli** [comment]
I tried `flatpak update` and it turns out that I just had to do some Nvidia updates.
